name: bagzz
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  dot_navigation_bar: ^1.0.1+4
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  http: ^0.13.5
  flutter_spinkit: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/review_images/
    - assets/images/bags_images/
    - assets/images/category_images/
    - assets/images/complete_payment/





  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 700
    - family: Trajan Pro
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf

 
